// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3U2Yl_ja9qPPBUumLtdSBO9Ho87vLA6w',
    appId: '1:1070632976958:web:fbb99d8736766a34fc476f',
    messagingSenderId: '1070632976958',
    projectId: 'fir-app-e5ad2',
    authDomain: 'fir-app-e5ad2.firebaseapp.com',
    databaseURL: 'https://fir-app-e5ad2-default-rtdb.firebaseio.com',
    storageBucket: 'fir-app-e5ad2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmF-L8BD2LQtH2kFi8u6ziRaPl3hLxv_0',
    appId: '1:1070632976958:android:1863aa56a6a3099ffc476f',
    messagingSenderId: '1070632976958',
    projectId: 'fir-app-e5ad2',
    databaseURL: 'https://fir-app-e5ad2-default-rtdb.firebaseio.com',
    storageBucket: 'fir-app-e5ad2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu51s5CXqZIxD5tJdfQjpEe8BUwJrC1EI',
    appId: '1:1070632976958:ios:ede19f0929d25dd4fc476f',
    messagingSenderId: '1070632976958',
    projectId: 'fir-app-e5ad2',
    databaseURL: 'https://fir-app-e5ad2-default-rtdb.firebaseio.com',
    storageBucket: 'fir-app-e5ad2.appspot.com',
    iosBundleId: 'com.example.fireChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu51s5CXqZIxD5tJdfQjpEe8BUwJrC1EI',
    appId: '1:1070632976958:ios:d96b58ecdc12928efc476f',
    messagingSenderId: '1070632976958',
    projectId: 'fir-app-e5ad2',
    databaseURL: 'https://fir-app-e5ad2-default-rtdb.firebaseio.com',
    storageBucket: 'fir-app-e5ad2.appspot.com',
    iosBundleId: 'com.example.fireChat.RunnerTests',
  );
}
